//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PocketSNES.rc
//
#define IDS_APP_TITLE                   1
#define IDS_HELLO                       2
#define IDC_POCKETSNES                  3
#define IDS_HELLO2                      4
#define IDS_PAUSED                      5
#define IDS_LINK                        6
#define IDS_CREDITS1                    7
#define IDS_CREDITS2                    8
#define IDS_CREDITS0                    9
#define IDI_POCKETSNES                  101
#define IDM_MENU                        102
#define IDS_HELP                        104
#define IDD_OPTIONS                     104
#define IDB_KEYPAD                      105
#define IDD_SKINS                       106
#define IDD_KEYS                        107
#define IDD_KEYS1                       108
#define IDD_CREDITS                     108
#define IDD_KEYS_NEW                    109
#define IDD_DISPLAY                     109
#define IDD_SOUND                       110
#define IDD_SETTINGS                    111
#define IDD_SYSTEM                      111
#define IDB_POCKETSNES                  114
#define IDB_6BUTTON                     115
#define IDB_4BUTTON                     118
#define IDI_LEFT_ARROW                  119
#define IDI_RIGHT_ARROW                 120
#define IDS_COMMAND1                    301
#define IDC_STATIC_TITLE                444
#define IDC_STATIC_TITLE2               445
#define IDC_TRANSPARENCY                1001
#define IDC_SOUND                       1002
#define IDC_ECHO                        1003
#define IDC_SYNC                        1004
#define IDC_SYNCSOUND                   1004
#define IDC_CUSTOM1                     1005
#define IDC_REVERSE                     1005
#define IDC_REVERSESTEREO               1005
#define IDC_STEREO                      1006
#define IDC_BUTTON_PREVIOUS             1007
#define IDC_INTERPOLATE                 1007
#define IDC_INTERPOLATESOUND            1007
#define IDC_BUTTON_SET                  1008
#define IDC_ALTDECODE                   1008
#define IDC_BUTTON_NEXT                 1009
#define IDC_ENVELOPEHEIGHT              1009
#define IDC_SMOOTHSTRETCH               1010
#define IDC_FIXFREQUENCY                1010
#define IDC_LANDSCAPE                   1011
#define IDC_BUTTON_UP                   1028
#define IDC_BUTTON_DOWN                 1029
#define IDC_BUTTON_LEFT                 1030
#define IDC_BUTTON_RIGHT                1031
#define IDC_BUTTON_B                    1032
#define IDC_BUTTON_A                    1033
#define IDC_BUTTON_Y                    1034
#define IDC_BUTTON_X                    1035
#define IDC_BUTTON_START                1036
#define IDC_BUTTON_SELECT               1037
#define IDC_BUTTON_L                    1038
#define IDC_BUTTON_R                    1039
#define IDC_STATIC_UP                   1040
#define IDC_STATIC_LEFT                 1041
#define IDC_STATIC_B                    1042
#define IDC_STATIC_Y                    1043
#define IDC_STATIC_START                1044
#define IDC_STATIC_L                    1045
#define IDC_STATIC_DOWN                 1046
#define IDC_STATIC_RIGHT                1047
#define IDC_STATIC_A                    1048
#define IDC_STATIC_X                    1049
#define IDC_STATIC_SELECT               1050
#define IDC_STATIC_R                    1051
#define IDC_STATIC_INFO                 1052
#define IDC_FRAMESKIP                   1053
#define IDC_SPIN_FRAMESKIP              1055
#define IDC_CREDITS                     1056
#define IDC_SIXTEENBIT                  1059
#define IDC_EIGHTBIT                    1060
#define IDC_SOUNDQUALITY                1061
#define IDC_LEFT                        1063
#define IDC_AUTO                        1065
#define IDC_COMPAT                      1066
#define IDC_CYCLES                      1067
#define IDC_CYCLES_SPIN                 1068
#define IDC_PORTRAIT                    1069
#define IDC_LANDLEFT                    1070
#define IDC_LANDLEFTSTRETCH             1071
#define IDC_LANDRIGHTSTRETCH            1072
#define IDC_LANDRIGHT                   1073
#define IDC_SLIDER1                     1074
#define IDC_FRAMESKIP_SLIDER            1074
#define IDC_SKIP                        1075
#define IDC_EDIT1                       1076
#define IDC_BROWSE                      1077
#define IDC_STARTLOADSTATE              1078
#define IDC_RESUMEAFTERLOADSTATE        1078
#define IDC_STARTSAVESTATE              1079
#define IDC_RESUMEAFTERSAVESTATE        1079
#define IDC_DISPLAYFRAMERATE            1080
#define IDC_SOUNDQUALITYTEXTBOX         1081
#define IDC_USEFOLDER                   1081
#define IDM_MAIN_COMMAND1               40001
#define IDM_HELP_ABOUT                  40003
#define IDM_FILE_LOAD                   40004
#define IDM_TOOLS_LOAD                  40004
#define ID_HELP                         40005
#define IDS_CAP_HELP                    40007
#define IDM_TOOLS_EXIT                  40008
#define IDS_CAP_OPTIONS                 40008
#define IDM_TOOLS_OPTIONS               40009
#define IDM_OPTIONS_SETTINGS            40009
#define IDM_TOOLS_SKINS                 40010
#define ID_OPTIONS                      40011
#define IDM_OPTIONS_KEYS                40013
#define IDM_TOOLS_CREDITS               40014
#define IDM_TOOLS_LOADSTATE             40015
#define IDM_TOOLS_SAVESTATE             40016
#define IDM_OPTIONS_DISPLAY             40017
#define IDM_OPTIONS_SOUND               40018
#define IDM_BLANK                       40020
#define IDM_OPTIONS_RESET               40022
#define IDM_TOOLS_RESET                 40022
#define IDM_LOAD1                       40023
#define IDM_TOOLS_LOAD1                 40023
#define IDM_LOAD2                       40024
#define IDM_TOOLS_LOAD2                 40024
#define IDM_LOAD3                       40025
#define IDM_TOOLS_LOAD3                 40025
#define IDM_LOAD4                       40026
#define IDM_TOOLS_LOAD4                 40026
#define IDM_LOAD5                       40027
#define IDM_TOOLS_LOAD5                 40027
#define IDM_HELP                        40029
#define IDM_SAVE1                       40031
#define IDM_TOOLS_SAVE1                 40031
#define IDM_SAVE2                       40032
#define IDM_TOOLS_SAVE2                 40032
#define IDM_SAVE3                       40033
#define IDM_TOOLS_SAVE3                 40033
#define IDM_SAVE4                       40034
#define IDM_LOAD6                       40035
#define IDM_TOOLS_LOAD6                 40035
#define IDM_LOAD7                       40036
#define IDM_TOOLS_LOAD7                 40036
#define IDM_LOAD8                       40037
#define IDM_SAVE6                       40038
#define IDM_TOOLS_SAVE6                 40038
#define IDM_SAVE7                       40039
#define IDM_TOOLS_SAVE7                 40039
#define IDM_SAVE8                       40040
#define IDM_TOOLS_SAVE8                 40040
#define IDM_SAVE9                       40041
#define IDM_TOOLS_SAVE9                 40041
#define IDM_TOOLS_SAVE4                 40042
#define IDM_TOOLS_SAVE5                 40043
#define IDM_TOOLS_RECENT1               40044
#define IDM_TOOLS_LOAD8                 40045
#define IDM_TOOLS_LOAD9                 40046
#define ID_OPTIONS_SYSTEM               40049
#define IDM_OPTIONS_SYSTEM              40049
#define IDM_CHEAT                       40050
#define IDS_CAP_CHEAT                   40052
#define IDM_NETPLAY                     40053
#define IDS_CAP_NETPLAY                 40055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40056
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
